apt:
  packages:
  - gcc-8-base 8.4.0-1ubuntu1~18.04 amd64
  - libblkid1 2.31.1-0.4ubuntu3.6 amd64
  - libbsd0 0.8.7-1ubuntu0.1 amd64
  - libc6 2.27-3ubuntu1 amd64
  - libdbus-1-3 1.12.2-1ubuntu1.1 amd64
  - libdouble-conversion1 2.0.1-4ubuntu1 amd64
  - libevdev2 1.5.8+dfsg-1 amd64
  - libexpat1 2.2.5-3ubuntu0.2 amd64
  - libffi6 3.2.1-8 amd64
  - libgcc1 1%3a8.4.0-1ubuntu1~18.04 amd64
  - libgcrypt20 1.8.1-4ubuntu1.2 amd64
  - libglib2.0-0 2.56.4-0ubuntu0.18.04.6 amd64
  - libgpg-error0 1.27-6 amd64
  - libgraphite2-3 1.3.11-2 amd64
  - libgudev-1.0-0 1%3a232-2 amd64
  - libharfbuzz0b 1.7.2-1ubuntu1 amd64
  - libice6 2%3a1.0.9-2 amd64
  - libicu60 60.2-3ubuntu3.1 amd64
  - libinput10 1.10.4-1ubuntu0.18.04.1 amd64
  - libjpeg-turbo8 1.5.2-0ubuntu5.18.04.3 amd64
  - libjpeg8 8c-2ubuntu8 amd64
  - liblz4-1 0.0~r131-2ubuntu3 amd64
  - liblzma5 5.2.2-1.3 amd64
  - libmount1 2.31.1-0.4ubuntu3.6 amd64
  - libmtdev1 1.1.5-1ubuntu3 amd64
  - libpciaccess0 0.14-1 amd64
  - libpcre3 2%3a8.39-9 amd64
  - libpng16-16 1.6.34-1ubuntu0.18.04.2 amd64
  - libqt5charts5 5.9.5-0ubuntu1 amd64
  - libqt5core5a 5.9.5+dfsg-0ubuntu2.5 amd64
  - libqt5dbus5 5.9.5+dfsg-0ubuntu2.5 amd64
  - libqt5gui5 5.9.5+dfsg-0ubuntu2.5 amd64
  - libqt5network5 5.9.5+dfsg-0ubuntu2.5 amd64
  - libqt5svg5 5.9.5-0ubuntu1 amd64
  - libqt5widgets5 5.9.5+dfsg-0ubuntu2.5 amd64
  - libselinux1 2.7-2build2 amd64
  - libsm6 2%3a1.2.2-1 amd64
  - libssl1.1 1.1.1-1ubuntu2.1~18.04.5 amd64
  - libstdc++6 8.4.0-1ubuntu1~18.04 amd64
  - libsystemd0 237-3ubuntu10.40 amd64
  - libudev1 237-3ubuntu10.40 amd64
  - libuuid1 2.31.1-0.4ubuntu3.6 amd64
  - libwacom-common 0.29-1 all
  - libwacom2 0.29-1 amd64
  - libxau6 1%3a1.0.8-1 amd64
  - libxcb-icccm4 0.4.1-1ubuntu1 amd64
  - libxcb-image0 0.4.0-1build1 amd64
  - libxcb-keysyms1 0.4.0-1 amd64
  - libxcb-randr0 1.13-2~ubuntu18.04 amd64
  - libxcb-render-util0 0.3.9-1 amd64
  - libxcb-sync1 1.13-2~ubuntu18.04 amd64
  - libxcb-util1 0.4.0-0ubuntu3 amd64
  - libxcb-xinerama0 1.13-2~ubuntu18.04 amd64
  - libxcb-xkb1 1.13-2~ubuntu18.04 amd64
  - libxcursor1 1%3a1.1.15-1 amd64
  - libxdamage1 1%3a1.1.4-3 amd64
  - libxdmcp6 1%3a1.1.2-3 amd64
  - libxext6 2%3a1.3.3-1 amd64
  - libxfixes3 1%3a5.0.3-1 amd64
  - libxi6 2%3a1.7.9-1 amd64
  - libxkbcommon-x11-0 0.8.2-1~ubuntu18.04.1 amd64
  - libxkbcommon0 0.8.2-1~ubuntu18.04.1 amd64
  - libxrender1 1%3a0.9.10-1 amd64
  - libxshmfence1 1.3-1 amd64
  - libxxf86vm1 1%3a1.1.4-1 amd64
  - xkb-data 2.23.1-1ubuntu1.18.04.1 all
  - zlib1g 1%3a1.2.11.dfsg-0ubuntu2 amd64
  sources:
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  - deb http://br.archive.ubuntu.com/ubuntu/ bionic main restricted
  - deb http://br.archive.ubuntu.com/ubuntu/ bionic multiverse
  - deb http://br.archive.ubuntu.com/ubuntu/ bionic universe
  - deb http://br.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe
    multiverse
  - deb http://br.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
  - deb http://br.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
  - deb http://br.archive.ubuntu.com/ubuntu/ bionic-updates universe
  - deb http://ppa.launchpad.net/webupd8team/atom/ubuntu bionic main
  - deb http://security.ubuntu.com/ubuntu bionic-security main restricted
  - deb http://security.ubuntu.com/ubuntu bionic-security multiverse
  - deb http://security.ubuntu.com/ubuntu bionic-security universe
dependencies:
- libxcb-render.so.0
- libGL.so.1
- libxcb.so.1
- libresolv.so.2
- libX11.so.6
- libxcb-glx.so.0
- libxcb-shm.so.0
- libz.so.1
- libEGL.so.1
- libdrm.so.2
- libgbm.so.1
- libxcb-xfixes.so.0
- ld-linux-x86-64.so.2
- libpthread.so.0
- libm.so.6
- libxcb-shape.so.0
- librt.so.1
- libfreetype.so.6
- libc.so.6
- libstdc++.so.6
- libdl.so.2
- libX11-xcb.so.1
- libgcc_s.so.1
- libfontconfig.so.1
