// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_sir_interface.cpp"
#include "EWIEGA46WW/moc_sir_menu.cpp"
#include "EWIEGA46WW/moc_sir_plot.cpp"
